### PR TITLE
Improvements into webservice layout for the huge bots

### LINKED ISSUE #115: Any idea how to sort the state machines?
My bot starts to have a HUGE number of functions :D I'm proud of that, and I reuse a lot of functions in a lot of things, it saves me time and bugs

BUT I have a little problem, I start to have a tree too much and it does not begin to be clear,

One of the "" problems "" is that when I use the same function in different behaviors they are seen in all, (example take items from the chest / floor)

I don't know from where starts / end the functions

Any advice on how to improve this?
I attach my tree of states

Screenshot_2

I was thinking of making each nested a dropodown / or a rectangle but I don't know if it could be more confusing

### PR DESCRIPTION
**Pull request by sefirosweb**
Hello guys, as I commented in some threads for huge bots it is quite difficult to manage what state it is in and the current interface does not help much

Therefore, I prepared some changes that I think can help the community

Changes:

- Added bar to resize the panel of behaviors and canvas
image

- Navigate within states doing double click on state, 
  - if clicked to "start" state, they will up 1 level, will be appears a "up arrow"
image

  - Only can navigate if the state have sub nested states, will be appears a "down arrow"
image

- The tree of nested behavior has been changed, I used a new library "tree.js" to help him to generate the new tree,
  - Added buttons to open all / close all / "auto open" to track the current state active it will open the states automatically
- Added a example using nested behaviors with typescript 
  - I think is important to have a typescript example to show to new users how can make it with better practices
  - For that i needed to add tsconfig.eslint.json to lint the code but ignore it from build
- Small issues fixed (name of state machine, types)

Preview: https://www.youtube.com/watch?v=-X3EefyDvJg

This ticket can be closed: https://github.com/PrismarineJS/mineflayer-statemachine/issues/115

### CODE REVIEW

**Comment by rom1504** [comment]
this is big

@sefirosweb would you like to keep maintaining this package ?

**Comment by sefirosweb** [comment]
Hello @rom1504 , yes there are many changes I tried to make it as small as possible, but with the fact that more data is required and a restructuring of the tree has led me to make this code,

For maintenance I would be happy to help, for me this tool is vital for large bots

**Comment by kaduvert** [comment]
I'm just getting into statemachine development and immediately noticed the primitive nature of the web-view, so this seems crazy useful!

sad to see it's stuck, is there no maintainer who can make sense of the changes or what's the problem with this?

**Comment by rom1504** [comment]
@kaduvert yes, can you try this PR?
If you like it better than master we can merge

**Comment by kaduvert** [comment]
yeah, seems like a good idea.
will start my statemachine endeavours off with this and give feedback once i think i've done enough statemachine stuff to have tested this thoroughly.

**Comment by kaduvert** [comment]
so after my statemachine developments i greatly preferred the experience of this over master, encountered no errors.
haven't looked much at the code but apart from some inconsistent styling / linting it seems to be fine

**Comment by sefirosweb** [comment]
Hey guys, could you please merge the pr? I have more ideas to improve the package but I don't want to mess the code anymore.

**Comment by sefirosweb** [comment]
@rom1504 any news from this topic?

**Comment by kaduvert** [comment]
@sefirosweb have you seen my PR?
as said, i have no issues with your code, but i noticed some inconsistent styling / linting.
i conveniently created a pull request for you to fix this: https://github.com/sefirosweb/mineflayer-statemachine/pull/1

if you could merge it i too would fully approve of these changes

**Comment by sefirosweb** [comment]
> @sefirosweb have you seen my PR? as said, i have no issues with your code, but i noticed some inconsistent styling / linting. i conveniently created a pull request for you to fix this: [sefirosweb#1](https://github.com/sefirosweb/mineflayer-statemachine/pull/1)
> 
> if you could merge it i too would fully approve of these changes

I didn't saw 🤣 , done i merge it!

**Review by kaduvert — APPROVED** [review]

**Comment by kaduvert** [comment]
@rom1504 why don't you merge this or #197 and #198 ?
it's all purely additions improving the project and no breaking changes.

i get that you're scared because there's no maintainer, but there's a small community taking care of this on which you can rely on to steer the project in the right direction.

don't overcomplicate things, if something doesn't work someone will create a pr to fix it. worst case you just revert a breaking pr?

**Pull request closed without merging**
