### PR TITLE
Static class usage

### PR DESCRIPTION
**Pull request by GenerelSchwerz**
This PR is breaking.

To alleviate some of the boilerplate (making new variables for every transition), I have abstracted the class creation process into the state-machine itself. Behaviors and nested machines alike are provided to the state machine in static form. Access to the individual classes are provided only while the class is active, usually through `shouldTransition`.

The examples are not yet complete, so consider this branch W.I.P.

### CODE REVIEW

**Comment by sefirosweb** [comment]
@GenerelSchwerz I see are you modifing the core of package, maybe you are developing your own package and this pr must be close?

**Comment by GenerelSchwerz** [comment]
> @GenerelSchwerz I see are you modifing the core of package, maybe you are developing your own package and this pr must be close?

Probably, I decided to open a PR in case the Prismarine devs wanted to switch. Probably  not though.

**Comment by GenerelSchwerz** [comment]
Typings within this version are vebose (to say the least) but are completely functional.

Added functionality:
```md
Backend/functionality
======================
1. immediate chained state switching.
-  re-iterate over transitions after change in case other transitions are now true.

2. multiple parent states for transitions.
-  provides strongly typed union for shouldTransition.

3. Wildcard implementation.
-  provided wildcard transitions will be checked regardless of currently active state.

# Frontend/utility
======================
1. Positions for states can be set per state machine instead of globally.
-  Positions are not provided on the behaviors themselves, instead they are provided to a handler.

2. Exit states will be colored.
-  Wildcard states may also become colored in the future.
```

**Comment by extremeheat** [comment]
As Frej mentioned on the Discord you can apply these changes on sefiros' [change_nested_layout_bar](https://github.com/sefirosweb/mineflayer-statemachine/tree/change_nested_layout_bar) branch to avoid a conflict later on after #172 gets merged

**Comment by GenerelSchwerz** [comment]
> As Frej mentioned on the Discord you can apply these changes on sefiros' [change_nested_layout_bar](https://github.com/sefirosweb/mineflayer-statemachine/tree/change_nested_layout_bar) branch to avoid a conflict later on after #172 gets merged

Sure, I can do that. :+1:

**Comment by rom1504** [comment]
@GenerelSchwerz this seems to be changing everything

could be considered to merge but only if you then want to maintain it. Is it the case?

**Comment by GenerelSchwerz** [comment]
I moved this PR to a new repository: https://github.com/GenerelSchwerz/mineflayer-static-statemachine

There are a lot of additions/improvements I have added to that project that I will try to move here in time.

**Pull request closed without merging**
